sudo: required
services:
    - docker

script:
    - echo "skipping tests"

after_success:
    - docker build -t vincegnzls/multi-client ./client
    - docker build -t vincegnzls/multi-nginx ./nginx
    - docker build -t vincegnzls/multi-server ./server
    - docker build -t vincegnzls/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push vincegnzls/multi-client
    - docker push vincegnzls/multi-nginx
    - docker push vincegnzls/multi-server
    - docker push vincegnzls/multi-worker

deploy:
    provider: elasticbeanstalk
    region: ap-southeast-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-southeast-1-913171412485
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
